namespace: default
 
env:
  HTTP_ADDR: :8080
 
image:
  name: you/rest
  tag: latest
  pull: IfNotPresent
 
deployment:
  timestamp: 2006-01-02T15:04:05
  replicas: 1
  container:
    name: go
    port: 8080
 
service:
  type: ClusterIP
  port: 8080
